### ISSUE TITLE
xdrip important apps profile 

### ISSUE THREAD

**Issue by Hitman997** [twinko/GTR-2-WF-Xdrip-EN#12]
Hello everyone, recently I get a message from xdrip -  "xdrip important apps profile" with a sound, how do I cancel it?

**Comment by twinko** [comment]
Hi, im really sorry but this is either an question for the official xdrip community or for artems xdrip version. Depends on what you have installed right now. 
Moreover you should definitly provide more info (what phone, which OS, what xdrip version, Screenshots, describtion when it appears - perhaps you noticed a pattern, Logs). No one can/will help you with this kind of problem describtion.


Following the links to the right places :)
offical xdrip: https://github.com/NightscoutFoundation/xDrip/issues
artem: https://bigdigital.home.blog/  or https://github.com/bigdigital/xDrip-miband/issues or https://www.patreon.com/xdrip_miband/posts

Regards
